### ISSUE TITLE
Dependency gedmo/doctrine-extensions on not declared

### ISSUE THREAD

**Issue by Jelle-S** [Opifer/Revisions#4]
I get the following error:
```
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "SoftDeleteableListener" from namespace "Gedmo\SoftDeleteable".
```

The error is fixed by requiring gedmo/doctrine-extensions. The class is used in `Opifer\Revisions\EventListener\RevisionListener`. Ideally this should not be a hard dependency IMHO (can probably be fixed with a `class_exists()`)

**Comment by rvanlaarhoven** [comment]
Thanks!
